### ISSUE TITLE
小问题

### ISSUE THREAD

**Issue by Harlber** [huiger/ScreenShotDemo#4]
- 部分机型的关键字是 `截图`
 - 屏幕高度需要实时获取（考虑部分刘海屏，可以随时展示/关闭刘海区域）

去年公司做过一个一样的需求，看了下，抄的基本是一个代码

**Comment by fengjuan** [comment]
> * 部分机型的关键字是 `截图`
> * 屏幕高度需要实时获取（考虑部分刘海屏，可以随时展示/关闭刘海区域）
> 
> 去年公司做过一个一样的需求，看了下，抄的基本是一个代码

我运行检测不到截屏
