### ISSUE TITLE
原理描述、代码 直接复制本人博客，却没有引用来源，请尊重原创。https://xiets.blog.csdn.net/article/details/52692163

### ISSUE THREAD

**Issue by xietansheng** [huiger/ScreenShotDemo#9]

**Comment by xietansheng** [comment]
原理描述、代码 直接复制本人博客，却没有引用来源，请尊重原创。[https://xiets.blog.csdn.net/article/details/52692163](https://xiets.blog.csdn.net/article/details/52692163)

**Comment by huiger** [comment]
不好意思，几年前的记录了。

已经加了来源至README
